[package]
name = "update-ssh-config"
version = "0.1.0"
authors = ["Noah Masur <noah.masur@take2games.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs-next = "1.0.1"
clap = "2.33.1"
anyhow = "1.0.31"
